# Generated by Django 5.2.17 on 2026-09-28 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=120, verbose_name='Namn')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Beskrivning')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pris (kr)')),
                ('rut_eligible', models.BooleanField(default=True, verbose_name='Ger RUT-avdrag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortering')),
            ],
            options={
                'verbose_name': 'Tilläggstjänst',
                'verbose_name_plural': 'Tilläggstjänster',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_area', models.PositiveIntegerField(verbose_name='Från (m²)')),
                ('max_area', models.PositiveIntegerField(blank=True, help_text='Tomt = ingen övre gräns', null=True, verbose_name='Till (m²)')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grundpris (kr)')),
                ('additional_price_per_sqm', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name="Tillägg per m² över 'Från' (kr)")),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Beskrivning')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Prisregel',
                'verbose_name_plural': 'Prisregler',
                'ordering': ['min_area'],
            },
        ),
    ]
