# Generated by Django 5.2.17 on 2026-09-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ort')),
                ('slug', models.SlugField(help_text='t.ex. malmo, angelholm', max_length=100, unique=True, verbose_name='URL-slug')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Kort beskrivning (kort/länk)')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Hero-rubrik')),
                ('hero_description', models.TextField(blank=True, verbose_name='Hero-text')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO-titel')),
                ('meta_description', models.CharField(blank=True, max_length=170, verbose_name='Meta-beskrivning')),
                ('introduction', models.TextField(blank=True, verbose_name='Introduktion')),
                ('local_content', models.TextField(blank=True, help_text='Unik text om flyttstädning i just denna ort. Nämn bara områden och förhållanden som stämmer.', verbose_name='Lokalt innehåll')),
                ('cta_text', models.CharField(blank=True, max_length=100, verbose_name='CTA-text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv (visas på sajten)')),
                ('is_indexed', models.BooleanField(default=False, help_text='Aktivera först när sidan har tillräckligt med unikt innehåll. Annars sätts noindex och sidan utesluts ur sitemap.', verbose_name='Indexeras av Google')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stad',
                'verbose_name_plural': 'Städer',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='cities_city_is_acti_bf0dca_idx')],
            },
        ),
        migrations.CreateModel(
            name='CityFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Fråga')),
                ('answer', models.TextField(verbose_name='Svar')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortering')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='cities.city')),
            ],
            options={
                'verbose_name': 'Vanlig fråga',
                'verbose_name_plural': 'Vanliga frågor',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
