# Generated by Django 5.2.17 on 2026-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Förnamn')),
                ('last_name', models.CharField(max_length=80, verbose_name='Efternamn')),
                ('email', models.EmailField(max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Meddelande')),
                ('status', models.CharField(choices=[('NEW', 'Ny'), ('HANDLED', 'Hanterad')], db_index=True, default='NEW', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meddelande',
                'verbose_name_plural': 'Meddelanden',
                'ordering': ['-created_at'],
            },
        ),
    ]
