# Generated by Django 5.2.17 on 2026-09-28 12:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='COMPANY_NAME', max_length=120, verbose_name='Företagsnamn')),
                ('key_office_enabled', models.BooleanField(default=False, help_text='Aktivera endast om företaget faktiskt har ett kontor där kunder kan lämna nycklar.', verbose_name='Erbjud nyckelavlämning på kontor')),
                ('min_booking_lead_days', models.PositiveSmallIntegerField(default=2, help_text='Tider närmare än så här i tid kan inte bokas online.', verbose_name='Minsta framförhållning (dagar)')),
                ('self_cleaning_oven_surcharge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Tillägg självrengörande ugn (kr)')),
                ('rut_enabled', models.BooleanField(default=False, help_text='Aktivera först när företaget är godkänt för RUT och procent/tak nedan är kontrollerade.', verbose_name='Visa och räkna med RUT-avdrag')),
                ('rut_percent', models.DecimalField(decimal_places=2, default=Decimal('50'), help_text='Kontrollera gällande procentsats hos Skatteverket.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='RUT-avdrag (% av arbetskostnad)')),
                ('rut_labor_share_percent', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Endast arbetskostnaden ger RUT-avdrag (t.ex. inte material/resor om de faktureras separat).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Andel av priset som är arbetskostnad (%)')),
                ('rut_max_deduction', models.DecimalField(decimal_places=2, default=Decimal('75000'), help_text='Taket gäller per person och år. Systemet känner inte till kundens tidigare utnyttjande.', max_digits=10, verbose_name='Tak för RUT-avdrag per bokning (kr)')),
            ],
            options={
                'verbose_name': 'Webbplatsinställningar',
                'verbose_name_plural': 'Webbplatsinställningar',
            },
        ),
    ]
