# Generated by Django 5.2.17 on 2026-09-28 12:36

import apps.bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Datum')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Anledning')),
            ],
            options={
                'verbose_name': 'Blockerat datum',
                'verbose_name_plural': 'Blockerade datum',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Förnamn')),
                ('last_name', models.CharField(max_length=80, verbose_name='Efternamn')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kund',
                'verbose_name_plural': 'Kunder',
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('start_time', models.TimeField(verbose_name='Starttid')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Sluttid')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bokningsbar')),
            ],
            options={
                'verbose_name': 'Bokningsbar tid',
                'verbose_name_plural': 'Bokningsbara tider',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'start_time'), name='uniq_slot_date_time')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=apps.bookings.models.generate_reference, editable=False, max_length=20, unique=True, verbose_name='Bokningsnummer')),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('time', models.TimeField(verbose_name='Tid')),
                ('area', models.PositiveIntegerField(verbose_name='Bostadsyta (m²)')),
                ('address', models.CharField(max_length=200, verbose_name='Adress')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postnummer')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Ort')),
                ('key_handling', models.CharField(choices=[('HOME', 'Kunden är hemma och öppnar'), ('OFFICE', 'Nyckel lämnas på kontor'), ('ALREADY_LEFT', 'Nycklar redan lämnade')], max_length=20, verbose_name='Nyckelhantering')),
                ('oven_type', models.CharField(choices=[('STANDARD', 'Vanlig ugn'), ('SELF_CLEANING', 'Självrengörande ugn')], default='STANDARD', max_length=20, verbose_name='Ugn')),
                ('notes', models.TextField(blank=True, verbose_name='Övrig information')),
                ('use_rut', models.BooleanField(default=True, verbose_name='Kunden vill använda RUT')),
                ('price_before_rut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pris före RUT (kr)')),
                ('rut_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='RUT-avdrag (kr)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Att betala (kr)')),
                ('price_snapshot', models.JSONField(default=dict, editable=False, verbose_name='Prisunderlag')),
                ('status', models.CharField(choices=[('NEW', 'Ny'), ('CONFIRMED', 'Bekräftad'), ('IN_PROGRESS', 'Pågående'), ('COMPLETED', 'Utförd'), ('CANCELLED', 'Avbokad')], db_index=True, default='NEW', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.availabilityslot')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.customer')),
            ],
            options={
                'verbose_name': 'Bokning',
                'verbose_name_plural': 'Bokningar',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='BookingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rut_eligible', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='bookings.booking')),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.extra')),
            ],
            options={
                'verbose_name': 'Bokat tillägg',
                'verbose_name_plural': 'Bokade tillägg',
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('slot',), name='uniq_active_booking_per_slot'),
        ),
    ]
